apiVersion: v1
kind: ConfigMap
metadata:
  name: camunda-config
data:
  DB_DRIVER: org.postgresql.Driver
  DB_URL: jdbc:postgresql://localhost:5432/camunda_test
  DB_USERNAME: postgres
  DB_PASSWORD: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_USER: postgres
  POSTGRES_DB: camunda_test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-app
  labels:
    enviroment: camunda
spec:
  selector:
    matchLabels:
      app: camunda-app
  replicas: 4
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: camunda-app
        enviroment: camunda
    spec:
      containers:
        - name: camunda-app
          image: danilbabkin/docker_camunda:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: camunda-config
        - name: postgres-camunda
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: camunda-config